[apps]
accessories-calculator="applications/calculator.svg"
accessories-character-map="applications/character-map.svg"
accessories-dictionary="applications/dictionary.svg"
accessories-text-editor="applications/text-editor.svg"
help-browser="applications/help.svg"
multimedia-volume-control="applications/audio.svg"
preferences-desktop-accessibility="applications/accessibility.svg"
preferences-desktop-font="applications/font.svg"
preferences-desktop-keyboard="devices/keyboard.svg"
preferences-desktop-locale="applications/locale.svg"
preferences-desktop-multimedia="applications/multimedia.svg"
preferences-desktop-screensaver="applications/screensaver.svg"
preferences-desktop-theme="applications/theme.svg"
preferences-desktop-wallpaer="applications/wallpaper.svg"
system-file-manager="applications/file-browser.svg"
system-software-install="applications/store.svg"
system-software-update="applications/store.svg"
utilities-system-monitor="applications/system-monitor.svg"
utilities-terminal="applications/terminal.svg"

[categories]
applications-accessories="categories/widgets.svg"
applications-development="categories/development.svg"
applications-engineering="categories/engineering.svg"
applications-games="categories/games.svg"
applications-graphics="categories/art.svg"
applications-internet="applications/web-browser.svg"
applications-multimedia="applications/multimedia.svg"
applications-office="applications/text-editor.svg"
applications-other="categories/other.svg"
applications-science="categories/science.svg"
applications-system="categories/system.svg"
applications-utilities="categories/utilities.svg"
preferences="categories/settings.svg"
preferences-desktop="applications/desktop-settings.svg"
preferences-desktop-peripherals="devices/keyboard.svg"
preferences-system-network="applications/network.svg"
system-help="applications/help.svg"

[devices]
audio-card="devices/pci-card.svg"
audio-input-microphone="devices/microphone.svg"
battery="devices/battery.svg"
camera="devices/camera.svg"
computer="devices/display.svg"
drive-harddisk="devices/hardisk.svg"
drive-optical="devices/disk.svg"
drive-removable-media="devices/usb.svg"
input-gaming="devices/gamepad.svg"
input-keyboard="devices/keyboard.svg"
input-mouse="devices/mouse.svg"
input-tablet="devices/phone.svg"
media="devices/disk.svg"
media-floppy="devices/floppy.svg"
multimedia-player="applications/audio.svg"
network-wired="devices/ethernet.svg"
network-wireless="devices/wifi.svg"
pda="devices/pda.svg"
phone="devices/phone.svg"
printer="devices/printer.svg"
scanner="devices/printer.svg"
video-display="devices/display.svg"

[mimetypes]
application-x-executable="files/executable.svg"
audio-x-generic="files/audio.svg"
font-x-generic="files/font.svg"
image-x-generic="files/photo.svg"
package-x-generic="files/package.svg"
text-html="files/code.svg"
text-x-generic="files/text.svg"
text-x-generic-template="files/code.svg"
text-x-script="files/script.svg"
video-x-generic="files/video.svg"
x-office="files/office.svg"
x-office-document="files/document.svg"
x-office-presentation="files/presentation.svg"
x-office-spreadsheet="files/spreadsheet.svg"

[places]
folder="files/folder.svg"
folder-remote="files/network-folder.svg"
start-here="logo.svg"
user-desktop="devices/display.svg"
user-home="applications/home.svg"
user-trash="applications/trash.svg"
folder-desktop="files/desktop-folder.svg"
folder-home="files/home-folder.svg"
folder-download="files/downloads-folder.svg"
folder-documents="files/documents-folder.svg"
folder-music="files/music-folder.svg"
folder-pictures="files/photos-folder.svg"
folder-trash="files/trash-folder.svg"
folder-videos="files/videos-folder.svg"
