[apps]
accessories-calculator="applications/calculator.svg"
accessories-character-map="applications/character-map.svg"
accessories-dictionary="applications/dictionary.svg"
accessories-text-editor="applications/text-editor.svg"
multimedia-volume="indicators/audio-loud.svg"
audio="indicators/audio-loud.svg"
preferences="categories/settings.svg"
preferences-desktop="applications/desktop-settings.svg"
preferences-desktop-accessibility="applications/accessibility.svg"
preferences-desktop-font="applications/font.svg"
preferences-desktop-keyboard="devices/keyboard.svg"
preferences-desktop-locale="applications/locale.svg"
preferences-desktop-multimedia="applications/multimedia.svg"
preferences-desktop-screensaver="applications/screensaver.svg"
preferences-desktop-theme="applications/theme.svg"
preferences-desktop-wallpaper="applications/wallpaper.svg"
preferences-desktop-tablet="devices/phone.svg"
preferences-desktop-gaming="devices/gamepad.svg"
preferences-desktop-mouse="devices/mouse.svg"
preferences-desktop-touchpad="devices/trackpad.svg"
preferences-desktop-peripherals="devices/keyboard.svg"
preferences-system-network="devices/network.svg"
preferences-desktop-sound="indicators/audio-loud.svg"
preferences-devices-printer="devices/printer.svg"
preferences-system-bluetooth="devices/bluetooth.svg"
preferences-system-power="actions/power-on.svg"
system="devices/cpu.svg"
system-file-manager="applications/file-browser.svg"
system-software-install="applications/store.svg"
system-software-update="applications/store.svg"
utilities-system-monitor="applications/system-monitor.svg"
utilities-terminal="applications/terminal.svg"
tools-check-spelling="applications/font.svg"
hwinfo="categories/system.svg"

[categories]
applications-accessories="categories/widgets.svg"
applications-development="categories/development.svg"
applications-engineering="categories/engineering.svg"
applications-games="categories/games.svg"
applications-graphics="categories/art.svg"
applications-internet="applications/web-browser.svg"
applications-multimedia="applications/multimedia.svg"
applications-office="applications/text-editor.svg"
applications-other="categories/other.svg"
applications-science="categories/science.svg"
applications-system="categories/system.svg"
applications-utilities="categories/utilities.svg"
system-help="applications/help.svg"
applications-all="categories/widgets.svg"

[devices]
kdeconnect="devices/phone.svg"
device="devices/usb.svg"
audio-card="devices/pci-card.svg"
audio-input-microphone="devices/microphone.svg"
battery="devices/battery.svg"
camera="devices/camera.svg"
computer="devices/display.svg"
drive-harddisk="devices/hardisk.svg"
drive-optical="devices/disk.svg"
drive-removable-media="devices/usb.svg"
input="devices/keyboard.svg"
input-touchpad="devices/trackpad.svg"
input-gamepad="devices/gamepad.svg"
input-gaming="devices/gamepad.svg"
input-keyboard="devices/keyboard.svg"
input-mouse="devices/mouse.svg"
input-tablet="devices/phone.svg"
media="devices/disk.svg"
media-floppy="devices/floppy.svg"
multimedia-player="applications/multimedia.svg"
network-wired="devices/ethernet.svg"
network-wireless="devices/wifi.svg"
network-bluetooth="devices/bluetooth.svg"
network-card="devices/pci-card.svg"
pda="devices/pda.svg"
phone="devices/phone.svg"
printer="devices/printer.svg"
scanner="devices/printer.svg"
video-display="devices/display.svg"
memory="devices/ram.svg"

[mimetypes]
application-x-generic="files/blank.svg"
application-x-executable="files/executable.svg"
audio-x-generic="files/audio.svg"
font-x-generic="files/font.svg"
image-x-generic="files/photo.svg"
package-x-generic="files/package.svg"
text-html="files/code.svg"
text-x-generic="files/text.svg"
text-x-generic-template="files/code.svg"
text-x-script="files/script.svg"
video-x-generic="files/video.svg"
x-office="files/office.svg"
x-office-document="files/document.svg"
x-office-presentation="files/presentation.svg"
x-office-spreadsheet="files/spreadsheet.svg"
x-office-drawing="files/vector.svg"
application-x-archive="files/archive.svg"

[places]
folder="places/folder.svg"
folder-remote="places/network-folder.svg"
start-here="logo.svg"
user-desktop="devices/display.svg"
user-home="places/home.svg"
user-trash="places/trash.svg"
folder-desktop="places/desktop-folder.svg"
folder-home="places/home-folder.svg"
folder-download="places/downloads-folder.svg"
folder-documents="places/documents-folder.svg"
folder-music="places/music-folder.svg"
folder-pictures="places/photos-folder.svg"
folder-trash="places/trash-folder.svg"
folder-videos="places/videos-folder.svg"
folder-favorites="places/favorites-folder.svg"
document-open-recent="files/blank.svg"
favorites="actions/star.svg"

[actions]
help="applications/help.svg"
system-lock-screen="actions/lock.svg"
search="actions/search.svg"
favorite="actions/star.svg"
bookmarks="actions/bookmark.svg"
application-menu="actions/menu.svg"
go-bottom="actions/bottom.svg"
go-top="actions/top.svg"
go-last="actions/last.svg"
go-first="actions/first.svg"
go-down="actions/down.svg"
go-up="actions/up.svg"
go-next="actions/next.svg"
go-previous="actions/back.svg"
system-hibernate="actions/sleep.svg"
system-suspend="actions/sleep.svg"
system-shutdown="actions/power-off.svg"
system-log-out="actions/logout.svg"
user="actions/user.svg"
system-users="actions/user.svg"
