[apps]
accessories-calculator="applications/calculator.svg"
accessories-character-map="applications/character-map.svg"
accessories-dictionary="applications/dictionary.svg"
accessories-text-editor="applications/text-editor.svg"
multimedia-volume="indicators/audio-loud.svg"
audio="indicators/audio-loud.svg"
preferences="categories/settings.svg"
preferences-desktop="applications/desktop-settings.svg"
preferences-desktop-accessibility="applications/accessibility.svg"
preferences-desktop-font="applications/font.svg"
preferences-desktop-keyboard="devices/keyboard.svg"
preferences-desktop-locale="applications/locale.svg"
preferences-desktop-multimedia="applications/multimedia.svg"
preferences-desktop-screensaver="applications/screensaver.svg"
preferences-desktop-theme="applications/theme.svg"
preferences-desktop-wallpaper="applications/wallpaper.svg"
preferences-desktop-tablet="devices/phone.svg"
preferences-desktop-gaming="devices/gamepad.svg"
preferences-desktop-mouse="devices/mouse.svg"
preferences-desktop-touchpad="devices/trackpad.svg"
preferences-desktop-peripherals="devices/keyboard.svg"
preferences-system-network="devices/network.svg"
preferences-desktop-sound="indicators/audio-loud.svg"
preferences-devices-printer="devices/printer.svg"
preferences-system-bluetooth="devices/bluetooth.svg"
preferences-system-power="actions/power-on.svg"
preferences-desktop-notification-bell="applications/bell.svg"
preferences-desktop-activities="actions/activities.svg"
preferences-system-windows="applications/window.svg"
preferences-desktop-filter="actions/filter.svg"
system="devices/cpu.svg"
system-file-manager="applications/file-browser.svg"
system-software-install="applications/store.svg"
system-software-update="applications/store.svg"
utilities-system-monitor="applications/system-monitor.svg"
utilities-terminal="applications/terminal.svg"
tools-check-spelling="applications/font.svg"
hwinfo="categories/system.svg"

[categories]
applications-accessories="categories/widgets.svg"
applications-development="categories/development.svg"
applications-engineering="categories/engineering.svg"
applications-games="categories/games.svg"
applications-graphics="categories/art.svg"
applications-internet="applications/web-browser.svg"
applications-multimedia="applications/multimedia.svg"
applications-office="applications/text-editor.svg"
applications-other="categories/other.svg"
applications-science="categories/science.svg"
applications-system="categories/system.svg"
applications-utilities="categories/utilities.svg"
system-help="applications/help.svg"
applications-all="categories/all.svg"

[devices]
kdeconnect="devices/phone.svg"
smartphone="devices/phone.svg"
device="devices/usb.svg"
audio-card="devices/pci-card.svg"
audio-input-microphone="devices/microphone.svg"
battery="devices/battery.svg"
camera="devices/camera.svg"
computer="devices/display.svg"
drive-harddisk="devices/harddrive.svg"
drive-optical="devices/disk.svg"
drive-removable-media="devices/usb.svg"
input="devices/keyboard.svg"
input-touchpad="devices/trackpad.svg"
input-gamepad="devices/gamepad.svg"
input-gaming="devices/gamepad.svg"
input-keyboard="devices/keyboard.svg"
input-mouse="devices/mouse.svg"
input-tablet="devices/phone.svg"
media="devices/disk.svg"
media-floppy="devices/floppy.svg"
multimedia-player="applications/multimedia.svg"
network-wired="devices/ethernet.svg"
network-wireless="indicators/wifi-high.svg"
network-bluetooth="devices/bluetooth.svg"
network-card="devices/pci-card.svg"
pda="devices/pda.svg"
phone="devices/phone.svg"
printer="devices/printer.svg"
scanner="devices/printer.svg"
video-display="devices/display.svg"
video-display-brightness="indicators/brightness-low.svg"
memory="devices/ram.svg"

[mimetypes]
application-x-generic="files/blank.svg"
application-x-executable="files/executable.svg"
audio-x-generic="files/audio.svg"
font-x-generic="files/font.svg"
image-x-generic="files/photo.svg"
package-x-generic="files/package.svg"
text-html="files/code.svg"
text-x-generic="files/text.svg"
text-x-generic-template="files/code.svg"
text-x-script="files/script.svg"
video-x-generic="files/video.svg"
x-office="files/office.svg"
x-office-document="files/document.svg"
x-office-presentation="files/presentation.svg"
x-office-spreadsheet="files/spreadsheet.svg"
x-office-drawing="files/vector.svg"
application-x-archive="files/archive.svg"

[places]
folder="places/folder.svg"
folder-remote="places/network-folder.svg"
start-here="logo.svg"
user-desktop="devices/display.svg"
user-home="places/home.svg"
user-trash="places/trash.svg"
folder-desktop="places/desktop-folder.svg"
folder-home="places/home-folder.svg"
folder-download="places/downloads-folder.svg"
folder-documents="places/documents-folder.svg"
folder-music="places/music-folder.svg"
folder-pictures="places/photos-folder.svg"
folder-trash="places/trash-folder.svg"
folder-videos="places/videos-folder.svg"
folder-favorites="places/favorites-folder.svg"
document-open-recent="files/blank.svg"
favorites="actions/star.svg"

[actions]
help-about="applications/help.svg"
system-lock-screen="actions/lock.svg"
search="actions/search.svg"
system-search="actions/search.svg"
preferences-system-search="actions/search.svg"
transsearch="actions/search.svg"
file-search="actions/search.svg"
edit-find="actions/search.svg"
compass="actions/compass.svg"
favorite="actions/star.svg"
bookmark="actions/bookmark.svg"
bookmarks="actions/bookmark.svg"
application-menu="actions/menu.svg"
menu="actions/menu.svg"
open-menu="actions/menu.svg"
go-bottom="actions/bottom.svg"
go-top="actions/top.svg"
go-last="actions/last.svg"
go-first="actions/first.svg"
go-down="actions/down.svg"
go-up="actions/up.svg"
go-next="actions/next.svg"
go-previous="actions/back.svg"
system-hibernate="actions/sleep.svg"
system-suspend="actions/sleep.svg"
system-shutdown="actions/power-off.svg"
system-log-out="actions/logout.svg"
system-switch-user="actions/user.svg"
system-reboot="actions/restart.svg"
user="actions/user.svg"
system-users="actions/user.svg"
brightness-high="indicators/brightness-high.svg"
brightness-low="indicators/brightness-low.svg"
configure="actions/configure.svg"
games-config="actions/configure.svg"
view-list="actions/details-view.svg"
view-list-icons="actions/icons-view.svg"
view-list-details="actions/details-view.svg"
view-list-tree="actions/tree-view.svg"
view-sidetree="actions/sidetree.svg"
view-visible="actions/visible.svg"
view-hidden="actions/hidden.svg"
view-right-new="actions/new-right.svg"
view-left-new="actions/new-left.svg"
view-sort="actions/sort.svg"
view-more="actions/more.svg"
view-more-horizontal="actions/more-horizontal.svg"
view-filter="actions/filter.svg"
dialog-filter="actions/filter.svg"
filter="actions/filter.svg"
pin="actions/pin.svg"
window-pin="actions/pin.svg"
edit-undo="actions/undo.svg"
edit-redo="actions/redo.svg"
edit-cut="actions/cut.svg"
edit-rename="actions/edit.svg"
edit-copy="actions/copy.svg"
edit-duplicate="actions/copy.svg"
document-duplicate="actions/copy.svg"
edit-paste="actions/clipboard.svg"
edit-clear="actions/backspace.svg"
edit-delete="places/trash.svg"
delete="places/trash.svg"
edit-link="actions/link.svg"
insert-link="actions/link.svg"
link="actions/link.svg"
special_paste="actions/clipboard.svg"
notification="actions/notification.svg"
notifications="actions/notification.svg"
activities="actions/activities.svg"
diag_activity="actions/activities.svg"
list-add="actions/add.svg"
gtk-add="actions/add.svg"
window-close="actions/close.svg"
dialog-close="actions/close.svg"
gtk-close="actions/close.svg"
dialog-cancel="actions/cancel.svg"
gtk-cancel="actions/cancel.svg"
albumfolder-properties="actions/configure.svg"
dialog-object-properties="actions/configure.svg"
document-properties="actions/configure.svg"
gtk-properties="actions/configure.svg"
tag-properties="actions/configure.svg"
archive="actions/compress.svg"
document-open="places/folder.svg"
folder-open="places/folder.svg"
document-share="actions/share.svg"
photo="applications/wallpaper.svg"
photos="applications/wallpaper.svg"
viewimage="applications/wallpaper.svg"
x-shape-image="applications/wallpaper.svg"
tab-new="actions/new-tab.svg"
window-new="applications/window.svg"
tag="actions/tag.svg"
trash="places/trash.svg"
albumfolder-user-trash="places/trash.svg"
image="applications/wallpaper.svg"
mail-attachment="actions/paperclip.svg"
info="actions/info.svg"
documentinfo="actions/info.svg"
autocorrection="actions/magic.svg"
tools-wizard="actions/magic.svg"
quickwizard="actions/magic.svg"
script-new="applications/terminal.svg"
dialog-scripts="applications/terminal.svg"
lock="actions/lock.svg"
unlock="actions/unlock.svg"
swap-panels="actions/pane-swap.svg"
speedometer="actions/speedometer.svg"
view-calendar="applications/calendar.svg"
system-run="actions/run.svg"

[status]
microphone-sensitivity="devices/microphone.svg"
network-wirelss-0="indicators/wifi-none.svg"
network-wireless-20="indicators/wifi-low.svg"
network-wireless-40="indicators/wifi-medium.svg"
network-wireless-60="indicators/wifi-medium.svg"
network-wireless-80="indicators/wifi-high.svg"
network-wireless-100="indicators/wifi-high.svg"
battery-000="indicators/battery-low.svg"
battery-010="indicators/battery-low.svg"
battery-020="indicators/battery-low.svg"
battery-030="indicators/battery-medium.svg"
battery-040="indicators/battery-medium.svg"
battery-050="indicators/battery-medium.svg"
battery-060="indicators/battery-medium.svg"
battery-070="indicators/battery-full.svg"
battery-080="indicators/battery-full.svg"
battery-100="indicators/battery-full.svg"
battery-empty="indicators/battery-low.svg"
battery-caution="indicators/battery-low.svg"
battery-low="indicators/battery-medium.svg"
battery-good="indicators/battery-full.svg"
battery-full="indicators/battery-full.svg"
night-light="indicators/nightlight.svg"
smartphonedisconnected="devices/phone.svg"
dialog-information="actions/info.svg"
showinfo="actions/info.svg"
data-information="actions/info.svg"
disk="devices/harddrive.svg"

[emotes]
face-smile="emoticons/smile.svg"
face-sad="emoticons/frown.svg"
